version: '3.9'
services: 
  mongo_db:
    container_name: yolodb
    image: mongo:latest
    environment: 
      MONGO_INITDB_DATABSE: yolomy
    restart: always 
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  backend:
    container_name: yolo_backend
    build: ./backend
    image: tanyaconny/yolo_backend:v.0.0
    ports:
      - 5000:5000
    volumes:
        - .:/app/yolo
    environment:
      PORTS: 5000
      MONGODB_URI: mongodb://mongo_db:27017/yolomy
      DB_NAME: yolomy
    depends_on: 
      - mongo_db

  client:
    container_name: yolo_client
    build: ./client
    image: tanyaconny/yolo_client:v.0.0
    tty: true
    ports:
      - 3000:3000
    environment:
      PORTS: 3000
      PROXY_API: http://backend:3000/
    depends_on:
      - backend

volumes:
  mongo_db: {}      
      
