# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: tanyaconny/yolo_client:v.0.0
          ports:
            - containerPort: 3000
        - name: yolo backend 
          image: tanyaconny/yolo_backend:v.0.0
          ports:
            - containerPort: 5000
        - name: db
          image: mongo:latest
          ports:
            - containerPort: 27017



---

# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
