apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend-deployment
  labels:
    app: yolo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
        - name: backend
          image: tanyaconny/yolo_backend:v.0.0
          ports:
            - containerPort: 5000
          env: 
            - name:  MONGODB_URI
              value: mongodb://database/yolomy